### ISSUE TITLE
feat(playbook-init): As a USER, I want to INIT a PLAYBOOK, so that I can create a new playbook folder

### ISSUE THREAD

**Issue by mightyhorst** [mitni455/playbook-sdk#7]
Relies on:

- [x] 1. selecting an example from the Examples Menu view in #13 
- [x] 2. The Examples Menu will be served Example Models from the Example Service #13 
- [x] 3. Refactor the PlaybookCtrl to use the Examples service rather than TEMPLATES const #14
- [x] 4. Create an ExampleModel #15 that extends the FileModel from #8 
- [x] 5. Typewriter #19 

### Reafctor 
* @todo REFACTOR 
- [x] 1. remove .getTemplate
- [x] 2. Load examples models from ExampleService 
 - [x] 3. Load them into a Menu View 
- [x] 4. Display as List 
- [x] 5. On select:
- [x] 6. copy the PlaybookJs file contents to the pwd 
- [x] 7. Copy the example folder to the pwd 
- [ ]  8. (no change) Slow print #19
